# Project 15. Modelo valor de mercado coches

El servicio de venta de autos usados Rusty Bargain está desarrollando una aplicación para atraer nuevos clientes. Gracias a esa app, puedes averiguar rápidamente el valor de mercado de tu coche. Tienes acceso al historial: especificaciones técnicas, versiones de equipamiento y precios. Tienes que crear un modelo que determine el valor de mercado.
A Rusty Bargain le interesa:
- la calidad de la predicción;
- la velocidad de la predicción;
- el tiempo requerido para el entrenamiento

## Preparación de datos

### Inicialización

In [37]:
import math
import numpy as np
import pandas as pd 

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, root_mean_squared_error

from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor

### Carga de datos

In [2]:
data = pd.read_csv('datasets/P15/car_data.csv')

### Información general y visualización inicial de datos

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 354369 entries, 0 to 354368
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   DateCrawled        354369 non-null  object
 1   Price              354369 non-null  int64 
 2   VehicleType        316879 non-null  object
 3   RegistrationYear   354369 non-null  int64 
 4   Gearbox            334536 non-null  object
 5   Power              354369 non-null  int64 
 6   Model              334664 non-null  object
 7   Mileage            354369 non-null  int64 
 8   RegistrationMonth  354369 non-null  int64 
 9   FuelType           321474 non-null  object
 10  Brand              354369 non-null  object
 11  NotRepaired        283215 non-null  object
 12  DateCreated        354369 non-null  object
 13  NumberOfPictures   354369 non-null  int64 
 14  PostalCode         354369 non-null  int64 
 15  LastSeen           354369 non-null  object
dtypes: int64(7), object(

In [4]:
data.head()

DateCrawled  Price VehicleType  RegistrationYear Gearbox  Power  \
0  24/03/2016 11:52    480         NaN              1993  manual      0   
1  24/03/2016 10:58  18300       coupe              2011  manual    190   
2  14/03/2016 12:52   9800         suv              2004    auto    163   
3  17/03/2016 16:54   1500       small              2001  manual     75   
4  31/03/2016 17:25   3600       small              2008  manual     69   

   Model  Mileage  RegistrationMonth  FuelType       Brand NotRepaired  \
0   golf   150000                  0    petrol  volkswagen         NaN   
1    NaN   125000                  5  gasoline        audi         yes   
2  grand   125000                  8  gasoline        jeep         NaN   
3   golf   150000                  6    petrol  volkswagen          no   
4  fabia    90000                  7  gasoline       skoda          no   

        DateCreated  NumberOfPictures  PostalCode          LastSeen  
0  24/03/2016 00:00                 0       70435  07/04/2016 03:16  
1  24/03/2016 00:00                 0       66954  07/04/2016 01:46  
2  14/03/2016 00:00                 0       90480  05/04/2016 12:47  
3  17/03/2016 00:00                 0       91074  17/03/2016 17:40  
4  31/03/2016 00:00                 0       60437  06/04/2016 10:17

In [5]:
data.sample(5)

DateCrawled  Price VehicleType  RegistrationYear Gearbox  Power  \
85177   16/03/2016 18:51   1799       small              2003  manual     75   
138253  17/03/2016 11:50   2400       coupe              1998    auto    136   
182237  14/03/2016 14:57  10400       sedan              2009  manual    190   
87743   21/03/2016 09:56   2400       sedan              1989    auto    132   
154017  13/03/2016 00:56   2699         NaN              2018     NaN      0   

           Model  Mileage  RegistrationMonth FuelType          Brand  \
85177     twingo   150000                  4   petrol        renault   
138253       clk   150000                  3   petrol  mercedes_benz   
182237       5er   150000                  1      NaN            bmw   
87743   e_klasse   150000                  9   petrol  mercedes_benz   
154017     fabia   150000                  0   petrol          skoda   

       NotRepaired       DateCreated  NumberOfPictures  PostalCode  \
85177           no  16/03/2016 00:00                 0       37696   
138253          no  17/03/2016 00:00                 0       52076   
182237          no  14/03/2016 00:00                 0       86650   
87743           no  21/03/2016 00:00                 0       27432   
154017         NaN  13/03/2016 00:00                 0       38302   

                LastSeen  
85177   07/04/2016 03:16  
138253  17/03/2016 12:39  
182237  15/03/2016 09:45  
87743   28/03/2016 03:46  
154017  13/03/2016 03:54

### Corrección y preparación de datos
En el paso anterior encontramos valores nulos presentes en diferentes columnas, sin embargo nuestro target:'Price' está completo, veamos como manejar estos datos. Así mismo, se observaron valores de 0 para la columna 'Power' lo cual es inconsistente y podría ser un error por tanto debemos hacer cambios en esta información. Verificaremos los valores de la columna 'NumberOfPictures' ya que tanto en la vista de los primeros 5 resultados y en la muestra aleatoria todos los resultados fueron de 0. Finalmente verificaremos que tan relevantes son algunas características para el target.

In [6]:
#Ya que nuestra columna target está completa reemplazaremos los valores nulos de las columnas:
#VehicleType, Gearbox, Model, FuelType y NotRepaired, por 'unknown' para no perder información
null_info_columns = ['VehicleType', 'Gearbox', 'Model', 'FuelType', 'NotRepaired']

data[null_info_columns] = data[null_info_columns].fillna('unknown')
data.info()
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 354369 entries, 0 to 354368
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   DateCrawled        354369 non-null  object
 1   Price              354369 non-null  int64 
 2   VehicleType        354369 non-null  object
 3   RegistrationYear   354369 non-null  int64 
 4   Gearbox            354369 non-null  object
 5   Power              354369 non-null  int64 
 6   Model              354369 non-null  object
 7   Mileage            354369 non-null  int64 
 8   RegistrationMonth  354369 non-null  int64 
 9   FuelType           354369 non-null  object
 10  Brand              354369 non-null  object
 11  NotRepaired        354369 non-null  object
 12  DateCreated        354369 non-null  object
 13  NumberOfPictures   354369 non-null  int64 
 14  PostalCode         354369 non-null  int64 
 15  LastSeen           354369 non-null  object
dtypes: int64(7), object(

DateCrawled  Price VehicleType  RegistrationYear Gearbox  Power  \
0  24/03/2016 11:52    480     unknown              1993  manual      0   
1  24/03/2016 10:58  18300       coupe              2011  manual    190   
2  14/03/2016 12:52   9800         suv              2004    auto    163   
3  17/03/2016 16:54   1500       small              2001  manual     75   
4  31/03/2016 17:25   3600       small              2008  manual     69   

     Model  Mileage  RegistrationMonth  FuelType       Brand NotRepaired  \
0     golf   150000                  0    petrol  volkswagen     unknown   
1  unknown   125000                  5  gasoline        audi         yes   
2    grand   125000                  8  gasoline        jeep     unknown   
3     golf   150000                  6    petrol  volkswagen          no   
4    fabia    90000                  7  gasoline       skoda          no   

        DateCreated  NumberOfPictures  PostalCode          LastSeen  
0  24/03/2016 00:00                 0       70435  07/04/2016 03:16  
1  24/03/2016 00:00                 0       66954  07/04/2016 01:46  
2  14/03/2016 00:00                 0       90480  05/04/2016 12:47  
3  17/03/2016 00:00                 0       91074  17/03/2016 17:40  
4  31/03/2016 00:00                 0       60437  06/04/2016 10:17

In [7]:
#Veamos como están distribuidos los valores de la columna 'Power'
data['Power'].describe()

count    354369.000000
mean        110.094337
std         189.850405
min           0.000000
25%          69.000000
50%         105.000000
75%         143.000000
max       20000.000000
Name: Power, dtype: float64

In [8]:
print(data['Power'].value_counts())

Power
0        40225
75       24023
60       15897
150      14590
101      13298
         ...  
1433         1
11025        1
1992         1
10910        1
15017        1
Name: count, Length: 712, dtype: int64


Vemos que hay valores en power que no tienen ningún sentido, valores de 0 o valores mayor a 1000 son practicamente imposibles y claramente afectarían nuestro modelo, debemos eliminar estos valores.

In [9]:
data = data[data['Power'] <= 1000]
data = data[data['Power'] > 0]
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 313842 entries, 1 to 354368
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   DateCrawled        313842 non-null  object
 1   Price              313842 non-null  int64 
 2   VehicleType        313842 non-null  object
 3   RegistrationYear   313842 non-null  int64 
 4   Gearbox            313842 non-null  object
 5   Power              313842 non-null  int64 
 6   Model              313842 non-null  object
 7   Mileage            313842 non-null  int64 
 8   RegistrationMonth  313842 non-null  int64 
 9   FuelType           313842 non-null  object
 10  Brand              313842 non-null  object
 11  NotRepaired        313842 non-null  object
 12  DateCreated        313842 non-null  object
 13  NumberOfPictures   313842 non-null  int64 
 14  PostalCode         313842 non-null  int64 
 15  LastSeen           313842 non-null  object
dtypes: int64(7), object(9)
me

Ahora que hemos hecho las correciones en la característica 'Power', veamos los valores de la columna 'NumberOfPictures':

In [10]:
print(data['NumberOfPictures'].value_counts())

NumberOfPictures
0    313842
Name: count, dtype: int64


In [11]:
#Ya que todos los valores de esta columna son 0, no aportará nada a nuestros modelos, por tanto la eliminaremos completamente
data =  data.drop(columns='NumberOfPictures', axis=1)
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 313842 entries, 1 to 354368
Data columns (total 15 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   DateCrawled        313842 non-null  object
 1   Price              313842 non-null  int64 
 2   VehicleType        313842 non-null  object
 3   RegistrationYear   313842 non-null  int64 
 4   Gearbox            313842 non-null  object
 5   Power              313842 non-null  int64 
 6   Model              313842 non-null  object
 7   Mileage            313842 non-null  int64 
 8   RegistrationMonth  313842 non-null  int64 
 9   FuelType           313842 non-null  object
 10  Brand              313842 non-null  object
 11  NotRepaired        313842 non-null  object
 12  DateCreated        313842 non-null  object
 13  PostalCode         313842 non-null  int64 
 14  LastSeen           313842 non-null  object
dtypes: int64(6), object(9)
memory usage: 38.3+ MB


Las características 'DateCrawled', 'DateCreated', 'PostalCode' y 'LastSeen' realmente no aportan mucha información directamente a nuestro target asi que pasaremos a eliminarlas tambien.

In [12]:
data = data.drop(columns=['DateCrawled', 'DateCreated', 'PostalCode', 'LastSeen'], axis=1)
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 313842 entries, 1 to 354368
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   Price              313842 non-null  int64 
 1   VehicleType        313842 non-null  object
 2   RegistrationYear   313842 non-null  int64 
 3   Gearbox            313842 non-null  object
 4   Power              313842 non-null  int64 
 5   Model              313842 non-null  object
 6   Mileage            313842 non-null  int64 
 7   RegistrationMonth  313842 non-null  int64 
 8   FuelType           313842 non-null  object
 9   Brand              313842 non-null  object
 10  NotRepaired        313842 non-null  object
dtypes: int64(5), object(6)
memory usage: 28.7+ MB


Veamos los valores de las demás características numéricas

In [13]:
#Empecemos por 'RegistrationYear'
print(data['RegistrationYear'].value_counts())
data['RegistrationYear'].describe()


RegistrationYear
1999    20149
2000    19401
2005    19200
2006    18725
2001    18258
        ...  
1933        1
8200        1
1947        1
1944        1
3500        1
Name: count, Length: 111, dtype: int64


count    313842.000000
mean       2003.483775
std          35.336413
min        1000.000000
25%        1999.000000
50%        2003.000000
75%        2008.000000
max        9999.000000
Name: RegistrationYear, dtype: float64

In [14]:
#Claramente el valor mínimo de 1000 o máximo de 9999 no tienen sentido debemos eliminar los valores que no tienen sentido
data = data[data['RegistrationYear'] < 2025]
data = data[data['RegistrationYear'] > 1900]
data['RegistrationYear'].describe()

count    313805.000000
mean       2003.247240
std           7.007376
min        1910.000000
25%        1999.000000
50%        2003.000000
75%        2008.000000
max        2019.000000
Name: RegistrationYear, dtype: float64

In [15]:
#verifiquemos la misma información para la columna 'RegistrationMonth'data['RegistrationMonth'].value_counts())
print(data['RegistrationMonth'].value_counts())
data['RegistrationMonth'].describe()

RegistrationMonth
3     31796
6     29030
4     27050
5     26896
7     25025
10    24019
12    22331
11    22068
0     21975
9     21908
1     21185
8     20755
2     19767
Name: count, dtype: int64


count    313805.000000
mean          5.934462
std           3.615522
min           0.000000
25%           3.000000
50%           6.000000
75%           9.000000
max          12.000000
Name: RegistrationMonth, dtype: float64

En el caso del mes, no eliminaremos aquellos donde el mes es 0 ya que lo interpretaremos como desconocido, sin embargo esta categoría la interpretaremos como categórica y reemplazaremos el mes '0' por 'unknown'.

In [16]:
data['RegistrationMonth'] = data['RegistrationMonth'].replace(0, 'unknown').astype(str)
print(data['RegistrationMonth'].value_counts())

RegistrationMonth
3          31796
6          29030
4          27050
5          26896
7          25025
10         24019
12         22331
11         22068
unknown    21975
9          21908
1          21185
8          20755
2          19767
Name: count, dtype: int64


In [17]:
#Veamos la ultima característica numérica
data['Mileage'].describe()

count    313805.000000
mean     128505.520945
std       36805.430101
min        5000.000000
25%      125000.000000
50%      150000.000000
75%      150000.000000
max      150000.000000
Name: Mileage, dtype: float64

Esta ultima columna presenta datos consistentes por tanto no haremos modificaciones en la misma.

In [18]:
#Veamos la distribucion de los valores de nuestro target
data['Price'].describe()

count    313805.000000
mean       4705.696209
std        4590.966346
min           0.000000
25%        1250.000000
50%        2999.000000
75%        6890.000000
max       20000.000000
Name: Price, dtype: float64

In [19]:
#Los valores de 'price' iguales a 0 realmente no nos ayuda para nuestro modelo, las eliminaremos
data = data[data['Price'] > 100]
data['Price'].describe()

count    305064.000000
mean       4840.219590
std        4585.977958
min         101.000000
25%        1350.000000
50%        3199.000000
75%        6990.000000
max       20000.000000
Name: Price, dtype: float64

## Entrenamiento del modelo 

Probaremos inicialmente 3 modelos: arbol de decisión, bosque aleatorio y regresión lineal. para esto utilizaremos 2 pipelines, una para los modelos basados en arbol donde codificaremos con OneHot las características categóricas unicamente, y el segundo para el modelo de regresión lineal donde se codificaran las características categóricas y escalaran las características numéricas con StandardScaler():

In [20]:
#Separemos las características categóricas de las numéricas
num_features = ['RegistrationYear', 'Power', 'Mileage']
cat_features = ['RegistrationMonth', 'VehicleType', 'Gearbox', 'Model', 'FuelType', 'Brand', 'NotRepaired']

In [21]:
num_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())])
cat_transformer =  Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [22]:
tree_preprocessor = ColumnTransformer(
    transformers=[('num', 'passthrough', num_features),
                 ('cat', cat_transformer, cat_features)])

linear_preprocessor = ColumnTransformer(
    transformers=[('num', num_transformer, num_features),
                 ('cat', cat_transformer, cat_features)])

In [23]:
tree_pipeline = Pipeline(steps=[
    ('tree_preprocessor', tree_preprocessor),
    ('model', DecisionTreeRegressor(random_state=12345, max_depth=5))])

rand_forest_pipeline = Pipeline(steps=[
    ('tree_preprocessor', tree_preprocessor),
    ('model', RandomForestRegressor(random_state=12345, n_estimators=100, max_depth=5))])

linreg_pipeline = Pipeline(steps=[
    ('linear_preprocessor', linear_preprocessor),
    ('model', LinearRegression())])

In [24]:
#división targets y features
features = data[num_features + cat_features]
target = data['Price']

features.info()
target.info()

<class 'pandas.core.frame.DataFrame'>
Index: 305064 entries, 1 to 354368
Data columns (total 10 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   RegistrationYear   305064 non-null  int64 
 1   Power              305064 non-null  int64 
 2   Mileage            305064 non-null  int64 
 3   RegistrationMonth  305064 non-null  object
 4   VehicleType        305064 non-null  object
 5   Gearbox            305064 non-null  object
 6   Model              305064 non-null  object
 7   FuelType           305064 non-null  object
 8   Brand              305064 non-null  object
 9   NotRepaired        305064 non-null  object
dtypes: int64(3), object(7)
memory usage: 25.6+ MB
<class 'pandas.core.series.Series'>
Index: 305064 entries, 1 to 354368
Series name: Price
Non-Null Count   Dtype
--------------   -----
305064 non-null  int64
dtypes: int64(1)
memory usage: 4.7 MB


In [25]:
#División en conjuntos de train y test
train_features, val_features, train_target, val_target = train_test_split(features, target, test_size=0.25, random_state=12345)

**Árbol de decisión**

In [26]:
%%time
#entrenemos el modelo de árbol
tree_pipeline.fit(train_features, train_target)
val_prediction_tree = tree_pipeline.predict(val_features)
print(root_mean_squared_error(val_target, val_prediction_tree))

2482.9491538755597
CPU times: total: 2.25 s
Wall time: 2.26 s


**Bosque Aleatorio**

In [27]:
%%time
rand_forest_pipeline.fit(train_features, train_target)
val_prediction_forest = rand_forest_pipeline.predict(val_features)
print(root_mean_squared_error(val_target, val_prediction_forest))

2424.759498616539
CPU times: total: 1min 16s
Wall time: 1min 16s


**Regresión Lineal**

In [28]:
%%time
linreg_pipeline.fit(train_features, train_target)
val_prediction_linreg = linreg_pipeline.predict(val_features)
print(root_mean_squared_error(val_target, val_prediction_linreg))

2638.2941291521847
CPU times: total: 32.3 s
Wall time: 4.75 s


**Prueba de cordura**:

In [29]:
baseline_prediction = pd.Series(train_target.mean(), index=val_target.index)
print(root_mean_squared_error(val_target, baseline_prediction))

4593.386468573785


Nuestros resultados indican claramente que nuestros modelos predicen, sin embargo el modelo con el mekor resultado es el de Bosque aleatorio, probemos realizar una validación cruzada con este modelo:

In [30]:
%%time
cv_scores = cross_val_score(rand_forest_pipeline,
                            features,
                            target,
                            cv=5,
                            scoring='neg_root_mean_squared_error')

rmse_scores = -cv_scores
print('RMSE medio:', rmse_scores.mean())

RMSE medio: 2434.524915211746
CPU times: total: 6min 35s
Wall time: 6min 37s


### Potenciación de gradiente:
**LightGBM**

In [31]:
%%time
lgbm_train_features = train_features.copy()
lgbm_val_features = val_features.copy()

for col in cat_features:
    lgbm_train_features[col] = lgbm_train_features[col].astype('category')
    lgbm_val_features[col] = lgbm_val_features[col].astype('category')

model = LGBMRegressor(n_estimators=500, random_state=12345)
model.fit(lgbm_train_features, train_target, categorical_feature=cat_features)
lgbm_val_predictions = model.predict(lgbm_val_features)

print('RMSE:', root_mean_squared_error(val_target, lgbm_val_predictions))

C:\Users\javie\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] El sistema no puede encontrar el archivo especificado
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "C:\Users\javie\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
        "wmic CPU Get NumberOfCores /Format:csv".split(),
        capture_output=True,
        text=True,
    )
  File "C:\Users\javie\anaconda3\Lib\subprocess.py", line 554, in run
    with Popen(*popenargs, **kwargs) as process:
         ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\javie\anaconda3\Lib\subprocess.py", line 1039, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006872 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 667
[LightGBM] [Info] Number of data points in the train set: 228798, number of used features: 10
[LightGBM] [Info] Start training from score 4838.317970
RMSE: 1561.4011710459604
CPU times: total: 27.7 s
Wall time: 2.14 s


**CatBoost**

CatBoost tampoco requiere de codificación de características categóricas:

In [32]:
%%time
model = CatBoostRegressor(iterations=500, depth=6, random_seed=12345)
model.fit(train_features, train_target, cat_features=cat_features, verbose=100)
cat_boost_val_predictions = model.predict(val_features)

print('RMSE:', root_mean_squared_error(val_target, cat_boost_val_predictions))

Learning rate set to 0.169711
0:	learn: 4085.7046490	total: 280ms	remaining: 2m 19s
100:	learn: 1703.8259382	total: 14.9s	remaining: 58.9s
200:	learn: 1631.8602975	total: 29.3s	remaining: 43.5s
300:	learn: 1597.9023772	total: 43.6s	remaining: 28.8s
400:	learn: 1573.5770983	total: 58.3s	remaining: 14.4s
499:	learn: 1555.2969716	total: 1m 12s	remaining: 0us
RMSE: 1623.7574911450254
CPU times: total: 11min 58s
Wall time: 1min 14s


**Validación cruzada LightGBM**

Ya que este fue el modelo con los mejores resultados realicemos una validación cruzada y veamos sus resultados

In [36]:
%%time
#debemos usar KFold ya que es el más sencillo para la validación cruzada en LightGBM
#Hemos seleccionado la división en 5 partes con el fin de que sea más corta la validación
kf = KFold(n_splits=5, shuffle=True, random_state=12345)
rmse_scores = []

for train_index, val_index in kf.split(features):
    features_train, features_val = features.iloc[train_index].copy(), features.iloc[val_index].copy()
    target_train, target_val = target.iloc[train_index], target.iloc[val_index]

    for col in cat_features:
        features_train[col] = features_train[col].astype('category')
        features_val[col] = features_val[col].astype('category')

    model = LGBMRegressor(n_estimators=300, random_state=12345)
    model.fit(features_train, target_train, categorical_feature=cat_features)

    cross_val_predictions = model.predict(features_val)
    rmse_scores.append(root_mean_squared_error(target_val, cross_val_predictions))

print('RMSE medio:', np.mean(rmse_scores))

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008532 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 670
[LightGBM] [Info] Number of data points in the train set: 244051, number of used features: 10
[LightGBM] [Info] Start training from score 4836.641030
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004172 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 668
[LightGBM] [Info] Number of data points in the train set: 244051, number of used features: 10
[LightGBM] [Info] Start training from score 4847.811822
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009717 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not

## Análisis del modelo

In [41]:
results = pd.DataFrame({
    'Modelo': ['Baseline', 'Linear', 'Decision Tree', 'Random Forest', 'CatBoost', 'LightGBM'],
    'RMSE': [4593, 2638, 2482, 2424, 1623, 1561],
    'Tiempo entrenamiento': ['-', '4.7s', '2.26s', '76s', '74s', '2.14s']
})
results

Modelo  RMSE Tiempo entrenamiento
0       Baseline  4593                    -
1         Linear  2638                 4.7s
2  Decision Tree  2482                2.26s
3  Random Forest  2424                  76s
4       CatBoost  1623                  74s
5       LightGBM  1561                2.14s

Despues de entrenar y probar los diferen modelos hemos obtenido que en cuanto a nuestros 3 modelos iniciales, el que presentó mejores resultados fue el modelo de Bosque aleatorio con un RMSE: 2424 que aumento ligeramente al realizar una prueba de validación cruzada ademas el timpo de ejecución de dicha celda fue de 1min16s y el de la validación cruzada fue 6min 15s, claramente un aumento sustancial. Para este modelo se realizó una codificación de características categróricas utilizando OneHotEncoder.

Sin embargo los mejores resultados fueron obtenidos con nuestros modelos de potenciación de gradiente obteniendo un RMSE: 1623 y un tiempo de 1min 14s para el modelo que utilizó CatBoost, una mejora bastante alta en comparación con el modelo de Bosque aleatorio. Y finalmente nuestro mejor modelo, el que utilizó LightGBM, donde obtuvimos un RMSE: 1561 con un tiempo de ejecución de 2.14 s, extremadamente veloz y con la mejor métrica, es claramente muy superior a los demás, y el recomendado con los resultados de este análisis.

Por supuesto, es importante mencionar que aunque evidentemente, como pudimos constatar con nuestra prueba de cordura para el modelo de regresión lineal, nuestros modelos predicen, los resultados no son los mejores y el error es bastante alto para una plataforma que busca valores apropiados para los vehiculos que pondrán a la venta los usuarios. Nuestro modelo claramente requiere mejoras para llegar a tener los resultados que requiere la empresa.

# Lista de control

Escribe 'x' para verificar. Luego presiona Shift+Enter

- [x]  Jupyter Notebook está abierto
- [x]  El código no tiene errores
- [x]  Las celdas con el código han sido colocadas en orden de ejecución
- [x]  Los datos han sido descargados y preparados
- [x]  Los modelos han sido entrenados
- [x]  Se realizó el análisis de velocidad y calidad de los modelos